### ISSUE TITLE
Show proper statuses in unlibrary and exchange

### ISSUE THREAD

**Issue by calebschoepp** [CMPUT301F20T24/Unlibrary#122]
The statuses for books in Unlibrary and Exchange should be different then what is stored in a book document on Firestore.

**Comment by armiantos** [comment]
Will wait for Accept flow PR to display ACCEPTED in Unlibrary

**Comment by armiantos** [comment]
I believe Unlibrary's status is already good as it is.
There are only 4 states for a Book object:
- Available - no one is requesting it, in which case unlibrary will never show the book
- Requested - someone is requesting it, if the requester is the current user unlibrary will show the book and list it as requested
- Accepted - if the current user is not the accepted requester, request will be archived and won't be displayed in un library
- Archived - will never be shown in Unlibrary because of the query

**Comment by armiantos** [comment]
Book in exchange appears as Requested even though I haven't requested it. Happens when someone else requests for the book.
