### ISSUE TITLE
RFC: Firestore data model

### ISSUE THREAD

**Issue by calebschoepp** [CMPUT301F20T24/Unlibrary#19]
The following is a rough outline of how I think we could model our data in Firestore.

### Root Collections
```
users {
  id: defaultID
  name: string  // Includes both first and last name
  username: string  // Must be globally unique
  email: string
  phone: string
  createdAt: timestamp // May not be useful
}
```

```
books {
  id: defaultID
  title: string
  author: string
  isbn: string
  status: string  // From enumeration of { available, requested, accepted, borrowed }
  photo: reference // A ref to a Firebase storage object (the image). This can be an array of references if multiple photos are required.
  owner: reference // A ref to the owning user document
  createdAt: // May not be useful  
}
```

```
requests {
  id: defaultID
  requester: reference // A ref to the requesting user document
  book: reference // A ref to the requested book document
  state: string // From enumeration of { requested, accepted, declined, received, returned, archived }, possibly add cancelled state?
  location: geopoint // This should be null if a request in any other state than accepted
  createdAt: timestamp // May not be useful
  
}
```

# Sample Workflows

## Library
- Query for all `books` of `username`
- For each `book` query for all non-archived `requests`

## Unlibrary
- Query for all non-archived `requests` where `requester` matches current user
- Use `book` reference to get book description

## Exchange
- Query for all `books` that aren't owned by current `user`
- Filter out books with `accepted` or `borrowed` states

# Notes
- Reading the spec it doesn't look like a book needs a "description". The description of a book appears to be the unique combination formed by `title` and `author` and `isbn`. Please correct me if I'm wrong.
- It doesn't appear that it is a requirement to have a profile picture for a user.
- IMO we are best off using the default IDs Firestore provides us unless a clear need for UUID's or some other custom ID is presented.

# Open Questions
- Does this schema cover all the requirements?
- How do we approach auth? Do we attempt to use Firebase Auth or is that more work than it is worth? Currently there are no requirements for password based authentication.

CC @CMPUT301F20T24/team-24

**Comment by cyrusdiego** [comment]
Had some notes: 

> Filter out books with accepted or borrowed states

I think for the Exchange workflow, we only want the books with `available` as it's status 

> Reading the spec it doesn't look like a book needs a "description". The description of a book appears to be the unique combination formed by title and author and isbn. Please correct me if I'm wrong.

I think you're correct. Reading over the spec, it implies the "description" is the title, author, and ISBN

> Does this schema cover all the requirements?

I think this schema covers the requirements, specs seem simple enough with the three objects modelling the requirements. 

> How do we approach auth? Do we attempt to use Firebase Auth or is that more work than it is worth? Currently there are no requirements for password based authentication.
 
I'd say we should air on side of caution regarding this, on one hand I feel like they won't ask us to do Auth but on the other hand, if they do then it would be nice if we had some familiarity or the framework ready to simply integrate. I'd say like a middle/low level priority? Not sure how hard it would be though, I've never done user auth before, would image it's just time-consuming to get this done rather than technically difficult per say. 

Overall looks good to me! Thanks for doing this :D

**Comment by cyrusdiego** [comment]
@calebschoepp can we close this issue and put the data modeling to the wiki?

**Comment by calebschoepp** [comment]
@cyrusdiego Fine by me
