### ISSUE TITLE
Research best practices on using Repositories

### ISSUE THREAD

**Issue by armiantos** [CMPUT301F20T24/Unlibrary#37]
- Find best practices on using Repositories and Firestore
- Refer to [App Architecture](https://developer.android.com/jetpack/guide)

TODO
- Knowledge share sometime this week or provide sample code in PR

**Comment by cyrusdiego** [comment]
this resource may be useful, it talks about good practice for storing livedata in the VM and repositories such that it doesn't cause memory leaks [link](https://medium.com/androiddevelopers/viewmodels-and-livedata-patterns-antipatterns-21efaef74a54)

**Comment by drojasca** [comment]
# Repositories
- The repository pattern is used to abstract away any interaction with the database from the ViewModel. 
- All code that relates to making any changes to the documents, is found in the repository (ie. Create, Save, Delete) 
- The rule of thumb is to have [one repository for each ViewModel](https://stackoverflow.com/questions/50466743/should-we-create-a-separate-repository-for-each-activity-or-single-repository-fo). This would make the code much more manageable and easily testable
- Firestore already has a caching mechanism that is enabled by default, so we do not need to implement it: [Link](https://stackoverflow.com/questions/52700648/how-to-avoid-unnecessary-firestore-reads-with-cache)
- When using [LiveData](https://developer.android.com/topic/libraries/architecture/livedata#java), it is recommended that the live data is held [within the repository](https://medium.com/androiddevelopers/viewmodels-and-livedata-patterns-antipatterns-21efaef74a54) to avoid memory leaks, and have another LiveData object in the ViewModel that would use a transformation to listen to the LiveData from the repository, and respect the lifecycle of the view.

# Realtime Updates
- I found this [video](https://www.youtube.com/watch?v=3aoxOtMM2rc&feature=emb_logo&ab_channel=Firebase) to be very helpful, but I summarized the important points below
- The Firesotre API allows for easy implementation of getting real-time updates
- There are two types of objects that can be used: **QuerySnapShot** and **DocumentSnapShot**
- **QuerySnapShot** allows you to listen to changes made to **any** document that would get returned by a query. See example [here]( https://firebase.google.com/docs/firestore/query-data/listen#listen_to_multiple_documents_in_a_collection)
- **DocumentSnapShot** allows you to listen to changes made to a **single** document in Firestore. See example [here]( https://firebase.google.com/docs/firestore/query-data/listen#events-local-changes)
- After a view is done being looked at, the listener must be detached, this can be done by keeping a [reference of the listener object, and then removing it from being active]( https://firebase.google.com/docs/firestore/query-data/listen#detach_a_listener)
- If you make a local change, your local snapshot would get updated first (even before the changes make it to firestore), after, when the database sends the new snapshot, the event listener would ignore it since it has already been updated
- Not exactly the same, but an idea of what it could all look like together can be found [here](https://stackoverflow.com/questions/59419258/what-relationship-between-firestore-snapshotlisteners-lifecycle-and-pricing)

# General Comments
- As I said above, I believe it would be best to contain the LiveData object in the repository itself, and then whenever any changes happen, it would first get updated in the repository, and then propagate into the ViewModel and view itself.
- I'm not sure how we want to handle getting data from the database, whether it's getting real-time updates or manually requesting every time. In the [video](https://www.youtube.com/watch?v=3aoxOtMM2rc&feature=emb_logo&ab_channel=Firebase) I linked above, the default should be realtime, and then argue why you shouldn't use realtime.
- I still need to talk to Cyrus about the changes to the architecture and where everything fits in.
- I am not sure how to handle conflicts in the database (ie. one user requests a book and the owner of the book deletes at the same time). My initial idea to have properties, but that's something would something that would need to be looked into more.
